"""Account ORM model and domain types for the Chart of Accounts.

Design overview
---------------
An **Account** is the fundamental unit of the Chart of Accounts (COA).
Every debit and credit in a journal entry references an Account.

Account type taxonomy
~~~~~~~~~~~~~~~~~~~~~
Five canonical types cover the full balance-sheet / income-statement
structure of double-entry bookkeeping:

``asset``
    Resources the company owns or controls (cash, AR, inventory…).
``liability``
    Obligations owed to external parties (AP, loans, accrued expenses…).
``equity``
    Residual interest after liabilities (retained earnings, capital…).
``income``
    Revenue earned from operations; increases equity.
``expense``
    Costs incurred in generating revenue; decreases equity.

Normal balance
~~~~~~~~~~~~~~
* **Debit-normal**: asset, expense — these accounts increase with debits.
* **Credit-normal**: liability, equity, income — these accounts increase
  with credits.

Hierarchy
~~~~~~~~~
Accounts can nest into a parent/child tree using ``parent_id``.
A child account **must** share the same :class:`AccountType` as its
parent (enforced in :class:`Account.__post_init__` and the ORM check
constraint).  Top-level ("header") accounts have ``parent_id = None``.

Multi-tenancy
~~~~~~~~~~~~~
Every account is scoped to a **Company** via the non-nullable
``company_id`` foreign key.  Accounts from different companies are
fully isolated.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from enum import Enum

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from cairnbooks.db import Base


def _utcnow() -> datetime:
    """Return the current UTC-aware datetime (used as a column default)."""
    return datetime.now(UTC)


# ---------------------------------------------------------------------------
# Value object — AccountType
# ---------------------------------------------------------------------------


class AccountType(str, Enum):
    """The five canonical account types in double-entry bookkeeping."""

    ASSET = "asset"
    LIABILITY = "liability"
    EQUITY = "equity"
    INCOME = "income"
    EXPENSE = "expense"

    @property
    def normal_balance(self) -> str:
        """Return ``'debit'`` or ``'credit'`` per accounting convention.

        * Debit-normal: ASSET, EXPENSE
        * Credit-normal: LIABILITY, EQUITY, INCOME
        """
        if self in (AccountType.ASSET, AccountType.EXPENSE):
            return "debit"
        return "credit"

    @property
    def is_balance_sheet(self) -> bool:
        """True for ASSET, LIABILITY, and EQUITY accounts."""
        return self in (AccountType.ASSET, AccountType.LIABILITY, AccountType.EQUITY)

    @property
    def is_income_statement(self) -> bool:
        """True for INCOME and EXPENSE accounts."""
        return self in (AccountType.INCOME, AccountType.EXPENSE)


# ---------------------------------------------------------------------------
# Domain exceptions
# ---------------------------------------------------------------------------


class AccountError(Exception):
    """Base exception for Account domain rule violations."""


class InvalidAccountCodeError(AccountError):
    """Raised when an account code is empty or whitespace-only."""


class InvalidAccountNameError(AccountError):
    """Raised when an account name is empty or whitespace-only."""


class AccountTypeMismatchError(AccountError):
    """Raised when a child account's type differs from its parent's type."""


class SelfReferenceError(AccountError):
    """Raised when an account's parent_id equals its own id."""


# ---------------------------------------------------------------------------
# ORM model — Account
# ---------------------------------------------------------------------------


class Account(Base):
    """Persistence model for the ``accounts`` table.

    Columns
    -------
    id
        UUID primary key, generated by PostgreSQL.
    company_id
        FK → ``companies.id`` (ON DELETE CASCADE).  Every account belongs
        to exactly one company.
    code
        Short human-readable code, unique per company (e.g. ``"1000"``,
        ``"4010"``).  Max 50 chars.
    name
        Human-readable label (e.g. ``"Cash"``, ``"Sales Revenue"``).
        Max 255 chars.
    type
        One of ``asset | liability | equity | income | expense``.
    parent_id
        Self-referential FK → ``accounts.id``; ``NULL`` for top-level
        accounts.  A child must share the same ``type`` as its parent
        (enforced by ``ck_accounts_type_matches_parent`` at the DB level
        via application logic, and by
        :meth:`assert_compatible_parent` at the domain level).
    active
        ``False`` means the account is archived and cannot receive new
        journal postings.
    created_at / updated_at
        Audit timestamps (UTC, timezone-aware).
    """

    __tablename__ = "accounts"

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="UUID primary key.",
    )

    # ------------------------------------------------------------------
    # Company scope
    # ------------------------------------------------------------------
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("companies.id", ondelete="CASCADE", name="fk_accounts_company_id"),
        nullable=False,
        index=True,
        comment="Owning company; accounts are isolated per company.",
    )

    # ------------------------------------------------------------------
    # Core fields
    # ------------------------------------------------------------------
    code: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="Short account code, unique within a company (e.g. '1000').",
    )

    name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Human-readable account name.",
    )

    type: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        comment="Account type: asset | liability | equity | income | expense.",
    )

    # ------------------------------------------------------------------
    # Self-referential parent / child hierarchy
    # ------------------------------------------------------------------
    parent_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("accounts.id", ondelete="RESTRICT", name="fk_accounts_parent_id"),
        nullable=True,
        index=True,
        comment="Parent account id; NULL for top-level (header) accounts.",
    )

    # ------------------------------------------------------------------
    # Status
    # ------------------------------------------------------------------
    active: Mapped[bool] = mapped_column(
        Boolean(),
        nullable=False,
        default=True,
        server_default=text("true"),
        comment="False means archived; account cannot receive new postings.",
    )

    # ------------------------------------------------------------------
    # Audit timestamps
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
        comment="Row insertion timestamp (UTC).",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
        server_default=text("now()"),
        comment="Last-update timestamp (UTC).",
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    children: Mapped[list[Account]] = relationship(
        "Account",
        back_populates="parent",
        foreign_keys=[parent_id],
        cascade="all, delete-orphan",
        lazy="raise",
    )

    parent: Mapped[Account | None] = relationship(
        "Account",
        back_populates="children",
        foreign_keys=[parent_id],
        remote_side=[id],
        lazy="raise",
    )

    # ------------------------------------------------------------------
    # Table-level constraints and composite indexes
    # ------------------------------------------------------------------
    __table_args__ = (
        # A top-level account cannot reference itself.
        CheckConstraint(
            "parent_id IS NULL OR parent_id <> id",
            name="ck_accounts_no_self_parent",
        ),
        # Account code must be unique within a company.
        UniqueConstraint("company_id", "code", name="uq_accounts_company_code"),
        # Common query pattern: active accounts of a given type in a company.
        Index("ix_accounts_company_type_active", "company_id", "type", "active"),
    )

    # ------------------------------------------------------------------
    # Domain methods (convenience layer; heavy logic belongs in services)
    # ------------------------------------------------------------------

    def is_compatible_parent(self, parent: Account) -> bool:
        """Return ``True`` if *parent* may be a valid parent for this account.

        A child must share the same :class:`AccountType` as its parent.
        """
        return self.type == parent.type

    def assert_compatible_parent(self, parent: Account) -> None:
        """Raise :class:`AccountTypeMismatchError` if the types differ.

        Raises
        ------
        AccountTypeMismatchError
            When ``parent.type != self.type``.
        """
        if not self.is_compatible_parent(parent):
            raise AccountTypeMismatchError(
                f"Cannot nest {self.type!r} account under "
                f"{parent.type!r} parent (account types must match)."
            )

    def deactivate(self) -> None:
        """Archive this account (set ``active = False``)."""
        self.active = False

    def activate(self) -> None:
        """Restore this account (set ``active = True``)."""
        self.active = True

    @property
    def normal_balance(self) -> str:
        """Return ``'debit'`` or ``'credit'`` based on this account's type.

        Delegates to :attr:`AccountType.normal_balance`.  Raises
        :class:`ValueError` if :attr:`type` is not a valid
        :class:`AccountType` value.
        """
        return AccountType(self.type).normal_balance

    def __repr__(self) -> str:
        return (
            f"<Account id={self.id!s} code={self.code!r} "
            f"type={self.type!r} active={self.active!r}>"
        )
