"""BankAccount ORM model — bank account linked to a GL account.

A BankAccount represents a real-world bank account belonging to a Company.
Each BankAccount is linked to exactly one GL (General Ledger) Account from
the Chart of Accounts (``accounts`` table), which receives the accounting
entries for all transactions flowing through the bank account.

Design notes
------------
* ``gl_account_id`` must reference an ``asset`` type Account (cash/bank).
  This constraint is enforced at the service / API layer rather than the DB
  level because PostgreSQL doesn't support cross-table check constraints.
* ``account_number`` and ``routing_number`` are optional and stored as plain
  text.  Callers are responsible for masking/encrypting sensitive digits
  before persisting.
* The ``active`` flag archives an account without deleting historical data.
  Archived accounts cannot receive new journal postings (enforced at the
  service layer).
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, String, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from cairnbooks.db import Base


def _utcnow() -> datetime:
    """Return the current UTC-aware datetime (used as a column default)."""
    return datetime.now(UTC)


class BankAccount(Base):
    """Persistence model for the ``bank_accounts`` table.

    Columns
    -------
    id
        UUID primary key, generated by PostgreSQL (or Python-side uuid4).
    company_id
        FK → ``companies.id`` (ON DELETE CASCADE).  Every bank account
        belongs to exactly one company.
    gl_account_id
        FK → ``accounts.id`` (ON DELETE RESTRICT).  The Chart-of-Accounts
        entry that mirrors this bank account (typically an asset account
        such as ``1010 – Checking Account``).
    name
        Human-readable label for the bank account (e.g. ``"Main Checking"``).
        Must be unique within a company.
    account_number
        Optional bank account number (store last-4 or masked value).
    routing_number
        Optional ABA routing / transit number.
    bank_name
        Optional name of the financial institution.
    currency
        ISO 4217 three-letter currency code; default ``"USD"``.
    active
        ``False`` means archived — the account is hidden from normal
        operations but its history is preserved.
    created_at / updated_at
        Audit timestamps (UTC, timezone-aware).
    """

    __tablename__ = "bank_accounts"

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="UUID primary key.",
    )

    # ------------------------------------------------------------------
    # Foreign keys
    # ------------------------------------------------------------------
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("companies.id", ondelete="CASCADE", name="fk_bank_accounts_company_id"),
        nullable=False,
        index=True,
        comment="Owning company; bank accounts are isolated per company.",
    )

    gl_account_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "accounts.id",
            ondelete="RESTRICT",
            name="fk_bank_accounts_gl_account_id",
        ),
        nullable=False,
        index=True,
        comment="Linked GL account from the Chart of Accounts.",
    )

    # ------------------------------------------------------------------
    # Core fields
    # ------------------------------------------------------------------
    name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Human-readable bank account name (e.g. 'Main Checking').",
    )

    account_number: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
        comment="Bank account number (plain or masked; e.g. last-4 digits).",
    )

    routing_number: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        comment="ABA routing / transit number.",
    )

    bank_name: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        comment="Name of the financial institution.",
    )

    currency: Mapped[str] = mapped_column(
        String(3),
        nullable=False,
        default="USD",
        server_default="USD",
        comment="ISO 4217 currency code (e.g. 'USD', 'EUR').",
    )

    # ------------------------------------------------------------------
    # Status
    # ------------------------------------------------------------------
    active: Mapped[bool] = mapped_column(
        Boolean(),
        nullable=False,
        default=True,
        server_default=text("true"),
        comment="False means archived; account unavailable for new transactions.",
    )

    # ------------------------------------------------------------------
    # Audit timestamps
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
        comment="Row insertion timestamp (UTC).",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
        server_default=text("now()"),
        comment="Last-update timestamp (UTC).",
    )

    # ------------------------------------------------------------------
    # Table-level constraints and composite indexes
    # ------------------------------------------------------------------
    __table_args__ = (
        # A company cannot have two bank accounts with the same name.
        UniqueConstraint(
            "company_id",
            "name",
            name="uq_bank_accounts_company_name",
        ),
        # Common query: list active bank accounts for a company.
        Index("ix_bank_accounts_company_active", "company_id", "active"),
    )

    # ------------------------------------------------------------------
    # Domain helpers
    # ------------------------------------------------------------------

    def deactivate(self) -> None:
        """Archive this bank account (set ``active = False``)."""
        self.active = False

    def activate(self) -> None:
        """Restore this bank account (set ``active = True``)."""
        self.active = True

    def __repr__(self) -> str:
        return (
            f"<BankAccount id={self.id!s} name={self.name!r} "
            f"company_id={self.company_id!s} active={self.active!r}>"
        )
