"""Item (Product/Service) ORM model.

Design overview
---------------
An **Item** represents a product or service that a company sells (income) or
purchases (expense).  Each item can be linked to:

* An **income account** — the revenue account credited when this item is sold
  on an invoice (e.g. "Sales Revenue").
* An **expense account** — the cost/expense account debited when this item
  appears on a bill (e.g. "Cost of Goods Sold", "Office Supplies").

Both account links are optional: a pure-service item might only have an income
account; a pure-purchase supply might only have an expense account.

Double-entry correctness
~~~~~~~~~~~~~~~~~~~~~~~~
When a sales-invoice line references this item, the posting engine will use
``income_account_id`` for the credit side.  When a bill/expense references this
item, it will use ``expense_account_id`` for the debit side.

Multi-tenancy
~~~~~~~~~~~~~
Every item is scoped to a **Company** via the non-nullable ``company_id``
foreign key.  Items from different companies are fully isolated.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, String, Text, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from cairnbooks.db import Base

if TYPE_CHECKING:
    from cairnbooks.models.account import Account
    from cairnbooks.models.company import Company


def _utcnow() -> datetime:
    """Return the current UTC-aware datetime (used as a column default)."""
    return datetime.now(UTC)


class Item(Base):
    """Persistence model for the ``items`` table.

    Columns
    -------
    id
        UUID primary key, generated by PostgreSQL.
    company_id
        FK → ``companies.id`` (ON DELETE CASCADE).  Every item belongs to
        exactly one company.
    name
        Human-readable product/service name.  Max 255 chars.  Required.
    description
        Optional longer description.  Stored as TEXT.
    income_account_id
        Optional FK → ``accounts.id`` (ON DELETE SET NULL).  The revenue account
        to credit when this item appears on a sales invoice.
    expense_account_id
        Optional FK → ``accounts.id`` (ON DELETE SET NULL).  The cost/expense
        account to debit when this item appears on a bill.
    active
        ``False`` means the item is archived and should not appear in new
        documents.
    created_at / updated_at
        Audit timestamps (UTC, timezone-aware).
    """

    __tablename__ = "items"

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="UUID primary key.",
    )

    # ------------------------------------------------------------------
    # Company scope
    # ------------------------------------------------------------------
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("companies.id", ondelete="CASCADE", name="fk_items_company_id"),
        nullable=False,
        index=True,
        comment="Owning company; items are isolated per company.",
    )

    # ------------------------------------------------------------------
    # Core fields
    # ------------------------------------------------------------------
    name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Product or service name.",
    )

    description: Mapped[str | None] = mapped_column(
        Text(),
        nullable=True,
        comment="Optional longer description.",
    )

    # ------------------------------------------------------------------
    # Account links
    # ------------------------------------------------------------------
    income_account_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "accounts.id",
            ondelete="SET NULL",
            name="fk_items_income_account_id",
        ),
        nullable=True,
        index=True,
        comment="Revenue account credited when this item is sold.",
    )

    expense_account_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "accounts.id",
            ondelete="SET NULL",
            name="fk_items_expense_account_id",
        ),
        nullable=True,
        index=True,
        comment="Cost/expense account debited when this item is purchased.",
    )

    # ------------------------------------------------------------------
    # Status
    # ------------------------------------------------------------------
    active: Mapped[bool] = mapped_column(
        Boolean(),
        nullable=False,
        default=True,
        server_default=text("true"),
        comment="False means archived; item should not appear in new documents.",
    )

    # ------------------------------------------------------------------
    # Audit timestamps
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
        comment="Row insertion timestamp (UTC).",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
        server_default=text("now()"),
        comment="Last-update timestamp (UTC).",
    )

    # ------------------------------------------------------------------
    # Relationships (lazy=raise prevents accidental N+1 queries)
    # ------------------------------------------------------------------
    company: Mapped[Company] = relationship(
        "Company",
        foreign_keys=[company_id],
        lazy="raise",
    )

    income_account: Mapped[Account | None] = relationship(
        "Account",
        foreign_keys=[income_account_id],
        lazy="raise",
    )

    expense_account: Mapped[Account | None] = relationship(
        "Account",
        foreign_keys=[expense_account_id],
        lazy="raise",
    )

    # ------------------------------------------------------------------
    # Table-level indexes
    # ------------------------------------------------------------------
    __table_args__ = (
        # Common query pattern: active items for a given company.
        Index("ix_items_company_active", "company_id", "active"),
    )

    def __repr__(self) -> str:
        return (
            f"<Item id={self.id!s} name={self.name!r} "
            f"company_id={self.company_id!s} active={self.active!r}>"
        )
