"""Journal and JournalLine ORM models for double-entry bookkeeping.

Design overview
---------------
A **Journal** is a dated accounting entry that groups one or more
:class:`JournalLine` rows.  For a valid double-entry posting the sum of
all debit amounts must equal the sum of all credit amounts.

Lifecycle
~~~~~~~~~
Journals begin in ``draft`` status.  Calling :meth:`Journal.post` promotes
them to ``posted``, at which point every :class:`JournalLine` becomes
**immutable**: any attempt to set a guarded column (:attr:`account_id`,
:attr:`debit`, :attr:`credit`, :attr:`description`, :attr:`line_number`)
raises :class:`JournalPostedError`.

Multi-tenancy
~~~~~~~~~~~~~
Every journal is scoped to a :class:`~cairnbooks.models.company.Company`
via ``company_id``.  Journal lines reference :class:`~cairnbooks.models.account.Account`
rows in the same company.

Table relationships
-------------------
    companies  1──*  journals  1──*  journal_lines  *──1  accounts
"""

from __future__ import annotations

import uuid
from datetime import UTC, date, datetime
from decimal import Decimal
from enum import StrEnum

from sqlalchemy import (
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship, validates

from cairnbooks.db import Base


def _utcnow() -> datetime:
    """Return the current UTC-aware datetime (used as a column default)."""
    return datetime.now(UTC)


# ---------------------------------------------------------------------------
# Value objects
# ---------------------------------------------------------------------------


class JournalStatus(StrEnum):
    """Lifecycle status of a :class:`Journal`."""

    DRAFT = "draft"
    POSTED = "posted"


# ---------------------------------------------------------------------------
# Domain exceptions
# ---------------------------------------------------------------------------


class JournalError(Exception):
    """Base exception for Journal domain rule violations."""


class JournalPostedError(JournalError):
    """Raised when a mutation is attempted on a posted journal or its lines."""


class JournalImbalancedError(JournalError):
    """Raised when debits ≠ credits at post time."""


# ---------------------------------------------------------------------------
# ORM model — Journal
# ---------------------------------------------------------------------------


class Journal(Base):
    """Persistence model for the ``journals`` table.

    Columns
    -------
    id
        UUID primary key, generated by PostgreSQL.
    company_id
        FK → ``companies.id`` (ON DELETE CASCADE).  Every journal belongs
        to exactly one company.
    date
        The accounting date of the entry (not necessarily the creation date).
    reference
        Optional external reference code (e.g. invoice number, receipt ID).
    description
        Optional free-text description of the journal entry.
    status
        ``draft`` (mutable) or ``posted`` (immutable lines).
    created_at / updated_at
        Audit timestamps (UTC, timezone-aware).
    """

    __tablename__ = "journals"

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="UUID primary key.",
    )

    # ------------------------------------------------------------------
    # Company scope
    # ------------------------------------------------------------------
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("companies.id", ondelete="CASCADE", name="fk_journals_company_id"),
        nullable=False,
        index=True,
        comment="Owning company; journals are isolated per company.",
    )

    # ------------------------------------------------------------------
    # Core fields
    # ------------------------------------------------------------------
    date: Mapped[date] = mapped_column(
        Date(),
        nullable=False,
        comment="Accounting date of the entry.",
    )

    reference: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        comment="Optional external reference (e.g. invoice number).",
    )

    description: Mapped[str | None] = mapped_column(
        Text(),
        nullable=True,
        comment="Optional free-text description of the entry.",
    )

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default=JournalStatus.DRAFT,
        server_default="draft",
        comment="Lifecycle status: draft | posted.",
    )

    # ------------------------------------------------------------------
    # Audit timestamps
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
        comment="Row insertion timestamp (UTC).",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
        server_default=text("now()"),
        comment="Last-update timestamp (UTC).",
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    lines: Mapped[list[JournalLine]] = relationship(
        "JournalLine",
        back_populates="journal",
        cascade="all, delete-orphan",
        lazy="raise",
        order_by="JournalLine.line_number",
    )

    # ------------------------------------------------------------------
    # Table-level constraints and indexes
    # ------------------------------------------------------------------
    __table_args__ = (
        CheckConstraint(
            "status IN ('draft', 'posted')",
            name="ck_journals_status",
        ),
        Index("ix_journals_company_date", "company_id", "date"),
    )

    # ------------------------------------------------------------------
    # Domain methods
    # ------------------------------------------------------------------

    @property
    def is_posted(self) -> bool:
        """Return ``True`` if this journal has been posted."""
        return self.status == JournalStatus.POSTED

    def assert_not_posted(self) -> None:
        """Raise :class:`JournalPostedError` if this journal is already posted.

        Raises
        ------
        JournalPostedError
            When :attr:`status` is ``posted``.
        """
        if self.is_posted:
            raise JournalPostedError(
                f"Journal {self.id} is posted and cannot be modified."
            )

    def post(self) -> None:
        """Promote this journal from ``draft`` → ``posted`` (irreversible).

        Once posted, every :class:`JournalLine` belonging to this journal
        becomes immutable — any attempt to change a guarded field raises
        :class:`JournalPostedError`.

        Raises
        ------
        JournalPostedError
            If the journal is already in ``posted`` status.
        """
        self.assert_not_posted()
        self.status = JournalStatus.POSTED

    def __repr__(self) -> str:
        return (
            f"<Journal id={self.id!s} date={self.date!s} status={self.status!r}>"
        )


# ---------------------------------------------------------------------------
# ORM model — JournalLine
# ---------------------------------------------------------------------------

# Columns that must not change once the parent journal is posted.
_GUARDED_LINE_FIELDS: frozenset[str] = frozenset(
    {"account_id", "debit", "credit", "description", "line_number"}
)


class JournalLine(Base):
    """One leg of a double-entry journal posting.

    Each line records a debit and/or credit amount against an account.
    By convention, exactly one of ``debit`` or ``credit`` is non-zero on
    a given line, but the schema allows both to be set (split-line
    bookkeeping).

    Amounts are stored as ``NUMERIC(19, 4)`` — four decimal places support
    currencies with up to four fractional digits (e.g. Japanese Yen needs
    zero; most ISO 4217 currencies need two; crypto may need four+).

    Immutability
    ~~~~~~~~~~~~
    When the parent :class:`Journal` carries ``status = 'posted'``, any
    attempt to mutate a guarded column raises :class:`JournalPostedError`.
    The guard is enforced via SQLAlchemy's ``@validates`` hook, which fires
    synchronously on every attribute assignment — no database round-trip is
    required.

    Columns
    -------
    id
        UUID primary key.
    journal_id
        FK → ``journals.id`` (ON DELETE CASCADE).
    account_id
        FK → ``accounts.id`` (ON DELETE RESTRICT — cannot delete an account
        that has posted lines).
    debit
        Debit amount; must be ≥ 0.  Defaults to ``0``.
    credit
        Credit amount; must be ≥ 0.  Defaults to ``0``.
    description
        Optional line-level annotation.
    line_number
        1-based display ordering of lines within the journal.
    created_at
        Row insertion timestamp (UTC).
    """

    __tablename__ = "journal_lines"

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="UUID primary key.",
    )

    # ------------------------------------------------------------------
    # Foreign keys
    # ------------------------------------------------------------------
    journal_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "journals.id",
            ondelete="CASCADE",
            name="fk_journal_lines_journal_id",
        ),
        nullable=False,
        comment="Parent journal entry.",
    )

    account_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "accounts.id",
            ondelete="RESTRICT",
            name="fk_journal_lines_account_id",
        ),
        nullable=False,
        comment="Account receiving this debit/credit.",
    )

    # ------------------------------------------------------------------
    # Debit / credit amounts
    # ------------------------------------------------------------------
    debit: Mapped[Decimal] = mapped_column(
        Numeric(precision=19, scale=4),
        nullable=False,
        default=Decimal("0"),
        server_default="0",
        comment="Debit amount (≥ 0).",
    )

    credit: Mapped[Decimal] = mapped_column(
        Numeric(precision=19, scale=4),
        nullable=False,
        default=Decimal("0"),
        server_default="0",
        comment="Credit amount (≥ 0).",
    )

    # ------------------------------------------------------------------
    # Optional annotation and ordering
    # ------------------------------------------------------------------
    description: Mapped[str | None] = mapped_column(
        Text(),
        nullable=True,
        comment="Optional line-level description / memo.",
    )

    line_number: Mapped[int] = mapped_column(
        Integer(),
        nullable=False,
        default=1,
        comment="1-based ordering of lines within the journal.",
    )

    # ------------------------------------------------------------------
    # Audit timestamp (lines are immutable once posted; no updated_at)
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
        comment="Row insertion timestamp (UTC).",
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    journal: Mapped[Journal] = relationship(
        "Journal",
        back_populates="lines",
        lazy="raise",
    )

    # ------------------------------------------------------------------
    # Table-level constraints and indexes
    # ------------------------------------------------------------------
    __table_args__ = (
        CheckConstraint("debit >= 0", name="ck_journal_lines_debit_nonneg"),
        CheckConstraint("credit >= 0", name="ck_journal_lines_credit_nonneg"),
        Index("ix_journal_lines_journal_id", "journal_id"),
        Index("ix_journal_lines_account_id", "account_id"),
    )

    # ------------------------------------------------------------------
    # Immutability guard
    # ------------------------------------------------------------------

    @validates(*_GUARDED_LINE_FIELDS)
    def _guard_posted(self, key: str, value: object) -> object:
        """Prevent mutation of guarded fields once the parent journal is posted.

        SQLAlchemy calls this validator synchronously whenever any of the
        guarded attributes (:attr:`account_id`, :attr:`debit`,
        :attr:`credit`, :attr:`description`, :attr:`line_number`) is set on
        the instance — including during construction.

        If the ``journal`` relationship has already been loaded into the
        instance dict (either because it was explicitly assigned or because
        it was eagerly fetched) and that journal's status is ``posted``, the
        assignment is rejected with :class:`JournalPostedError`.

        Checking ``self.__dict__.get("journal")`` avoids triggering a lazy
        load (which would require a live database session) — it inspects only
        what is already present in memory.

        Parameters
        ----------
        key:
            Name of the attribute being set.
        value:
            The proposed new value.

        Returns
        -------
        object
            *value* unchanged when the guard passes.

        Raises
        ------
        JournalPostedError
            When the parent journal is in ``posted`` status.
        """
        journal: Journal | None = self.__dict__.get("journal")
        if journal is not None and journal.status == JournalStatus.POSTED:
            raise JournalPostedError(
                f"Cannot set {key!r} on a line whose parent journal is already posted."
            )
        return value

    def __repr__(self) -> str:
        return (
            f"<JournalLine id={self.id!s} "
            f"debit={self.debit} credit={self.credit}>"
        )
