"""FiscalPeriod ORM model for date-range based accounting period management.

Design overview
---------------
A **FiscalPeriod** represents a named accounting period (e.g. "January 2026",
"2026-Q1") that is either ``open`` (postings allowed) or ``closed``
(postings blocked).

Lifecycle
~~~~~~~~~
Periods begin in ``open`` status.  Calling :meth:`FiscalPeriod.close`
transitions them to ``closed`` (irreversible).  Once closed, any attempt to
post a journal entry whose accounting date falls within
``[start_date, end_date]`` raises :class:`FiscalPeriodClosedError`.

Multi-tenancy
~~~~~~~~~~~~~
Every fiscal period is scoped to a :class:`~cairnbooks.models.company.Company`
via ``company_id``.

Table relationships
-------------------
    companies  1──*  fiscal_periods
"""

from __future__ import annotations

import uuid
from datetime import UTC, date, datetime
from enum import StrEnum

from sqlalchemy import (
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    String,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from cairnbooks.db import Base


def _utcnow() -> datetime:
    """Return the current UTC-aware datetime (used as a column default)."""
    return datetime.now(UTC)


# ---------------------------------------------------------------------------
# Value objects
# ---------------------------------------------------------------------------


class PeriodStatus(StrEnum):
    """Lifecycle status of a :class:`FiscalPeriod`."""

    OPEN = "open"
    CLOSED = "closed"


# ---------------------------------------------------------------------------
# Domain exceptions
# ---------------------------------------------------------------------------


class FiscalPeriodError(Exception):
    """Base exception for FiscalPeriod domain rule violations."""


class FiscalPeriodClosedError(FiscalPeriodError):
    """Raised when a posting is attempted within a closed fiscal period.

    This is the guard that enforces the accounting rule: once a period is
    closed, no new journal entries may be dated within its date range.
    """


class FiscalPeriodAlreadyClosedError(FiscalPeriodError):
    """Raised when :meth:`FiscalPeriod.close` is called on an already-closed period."""


# ---------------------------------------------------------------------------
# ORM model — FiscalPeriod
# ---------------------------------------------------------------------------


class FiscalPeriod(Base):
    """Persistence model for the ``fiscal_periods`` table.

    Columns
    -------
    id
        UUID primary key, generated by PostgreSQL.
    company_id
        FK → ``companies.id`` (ON DELETE CASCADE).  Every period belongs to
        exactly one company.
    name
        Human-readable label (e.g. ``"January 2026"``, ``"2026-Q1"``).
    start_date
        First day of the period (inclusive).
    end_date
        Last day of the period (inclusive).  Must be ≥ ``start_date``.
    status
        ``open`` (postings allowed) or ``closed`` (postings blocked).
    closed_at
        UTC timestamp recorded when the period was closed.  ``NULL`` while
        the period is still open.
    created_at / updated_at
        Audit timestamps (UTC, timezone-aware).
    """

    __tablename__ = "fiscal_periods"

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="UUID primary key.",
    )

    # ------------------------------------------------------------------
    # Company scope
    # ------------------------------------------------------------------
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "companies.id",
            ondelete="CASCADE",
            name="fk_fiscal_periods_company_id",
        ),
        nullable=False,
        comment="Owning company; fiscal periods are isolated per company.",
    )

    # ------------------------------------------------------------------
    # Core fields
    # ------------------------------------------------------------------
    name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Human-readable period label (e.g. '2026-Q1', 'January 2026').",
    )

    start_date: Mapped[date] = mapped_column(
        Date(),
        nullable=False,
        comment="First day of the period (inclusive).",
    )

    end_date: Mapped[date] = mapped_column(
        Date(),
        nullable=False,
        comment="Last day of the period (inclusive).",
    )

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default=PeriodStatus.OPEN,
        server_default="open",
        comment="Lifecycle status: open | closed.",
    )

    closed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when the period was closed (UTC). NULL while open.",
    )

    # ------------------------------------------------------------------
    # Audit timestamps
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
        comment="Row insertion timestamp (UTC).",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
        server_default=text("now()"),
        comment="Last-update timestamp (UTC).",
    )

    # ------------------------------------------------------------------
    # Table-level constraints and indexes
    # ------------------------------------------------------------------
    __table_args__ = (
        CheckConstraint(
            "status IN ('open', 'closed')",
            name="ck_fiscal_periods_status",
        ),
        CheckConstraint(
            "end_date >= start_date",
            name="ck_fiscal_periods_date_range",
        ),
        Index("ix_fiscal_periods_company_id", "company_id"),
        Index(
            "ix_fiscal_periods_company_dates",
            "company_id",
            "start_date",
            "end_date",
        ),
    )

    # ------------------------------------------------------------------
    # Convenience properties
    # ------------------------------------------------------------------

    @property
    def is_closed(self) -> bool:
        """Return ``True`` if this period has been closed."""
        return self.status == PeriodStatus.CLOSED

    @property
    def is_open(self) -> bool:
        """Return ``True`` if this period is still open."""
        return self.status == PeriodStatus.OPEN

    # ------------------------------------------------------------------
    # Domain methods
    # ------------------------------------------------------------------

    def contains_date(self, entry_date: date) -> bool:
        """Return ``True`` if *entry_date* falls within ``[start_date, end_date]``.

        Parameters
        ----------
        entry_date:
            The accounting date to test.
        """
        return self.start_date <= entry_date <= self.end_date

    def assert_posting_allowed(self, entry_date: date) -> None:
        """Raise :class:`FiscalPeriodClosedError` if *entry_date* falls in a closed period.

        When the period is ``open`` this method is a no-op regardless of
        *entry_date*.  When the period is ``closed``, it only raises if
        *entry_date* is within ``[start_date, end_date]`` — dates outside
        the period's range are unaffected.

        Parameters
        ----------
        entry_date:
            The accounting date of the proposed journal entry.

        Raises
        ------
        FiscalPeriodClosedError
            When this period is closed and *entry_date* falls within the period.
        """
        if self.is_closed and self.contains_date(entry_date):
            raise FiscalPeriodClosedError(
                f"Fiscal period {self.name!r} is closed; "
                f"cannot post entry dated {entry_date} "
                f"(period covers {self.start_date} – {self.end_date})."
            )

    def close(self) -> None:
        """Mark this period as closed, blocking future postings within its date range.

        The transition is irreversible: once a period is closed it cannot be
        reopened.  The timestamp is recorded in :attr:`closed_at`.

        Raises
        ------
        FiscalPeriodAlreadyClosedError
            If the period is already in ``closed`` status.
        """
        if self.is_closed:
            raise FiscalPeriodAlreadyClosedError(
                f"Fiscal period {self.name!r} is already closed."
            )
        self.status = PeriodStatus.CLOSED
        self.closed_at = _utcnow()

    def __repr__(self) -> str:
        return (
            f"<FiscalPeriod id={self.id!s} name={self.name!r} "
            f"status={self.status!r} {self.start_date}–{self.end_date}>"
        )
